import type { Element, Root, Text } from 'hast'
import type { Plugin } from 'unified'
import { visit } from 'unist-util-visit'

/**
 * Rehype plugin that detects the `> ` prefix on heading text
 * and strips it from the rendered output.
 *
 * Markdown convention:
 * ```md
 * ## > API Reference
 * ```
 *
 * The `> ` prefix is stripped from the heading text in the HTML output,
 * and a `data-collapsible` attribute is added to the heading element.
 *
 * The heading ID (generated by rehype-slug) is unaffected because
 * github-slugger already strips the `>` character.
 *
 * Note: This plugin runs AFTER fumadocs extracts the TOC, so the TOC
 * items retain the `> ` prefix — which the InlineTOC component uses
 * to detect collapsible sections.
 */

const COLLAPSIBLE_PREFIX = '> '
const HEADING_TAGS = new Set(['h1', 'h2', 'h3', 'h4', 'h5', 'h6'])

export const rehypeCollapsibleHeadings: Plugin<[], Root> = () => {
  return (tree) => {
    visit(tree, 'element', (node: Element) => {
      if (!HEADING_TAGS.has(node.tagName)) return

      const firstChild = node.children[0]
      if (firstChild?.type !== 'text') return

      const textNode = firstChild as Text
      if (!textNode.value.startsWith(COLLAPSIBLE_PREFIX)) return

      // Strip the `> ` prefix from the rendered heading text
      textNode.value = textNode.value.slice(COLLAPSIBLE_PREFIX.length)

      // Mark the heading element as collapsible
      node.properties ??= {}
      node.properties.dataCollapsible = 'true'
    })
  }
}
